apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
type: Opaque
data:
  USER_MONGODB_URI: "" # set this to your MongoDB URI (base64 encoded)
  GMAIL_USER: "" # set this to your Gmail user (for user email verification) (base64 encoded)
  GMAIL_PASS: "" # set this to your Gmail password (for user email verification) (base64 encoded)
