apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "peerprepapi"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-set-headers: "true"
    nginx.org/websocket-services: "matching-service, collab-service"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - peerprepapi.delishad.com # Your domain
      secretName: peerprep-tls # The secret that contains the TLS certificate and private key
  rules:
    - host: peerprepapi.delishad.com # Specify the host for the rules
      http:
        paths:
          - path: /users(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: user-service
                port:
                  number: 8004
          - path: /matching(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: matching-service
                port:
                  number: 8002
          - path: /collab(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: collab-service
                port:
                  number: 8010
          - path: /questions(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: question-service
                port:
                  number: 8003
