version: '3'
services:
  redis:
    image: redis:latest
    container_name: test-redis-container
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - ./redis-data:/data
    # expose ports when testing
    # ports:
    #   - "6379:6379"

  g38-matching-service:
    image: delishad21/g38-matching-service:latest
    env_file:
      - .env  # Loads environment variables from .env file
    ports:
      - "${MATCHING_SERVICE_PORT}:${MATCHING_SERVICE_PORT}"  # Bind port using env variable
    depends_on:
      - redis
    volumes:
      - ${MATCHING_SERVICE_LOGS_DIR}:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MATCHING_SERVICE_PORT}/api"]
      interval: 10s
      timeout: 5s
      retries: 5
