version: '3'
services:
  collab-redis:
    image: redis:latest
    container_name: collab-redis
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - ./collab-redis-data:/data
    # expose ports when testing
    # ports:
    #   - "6369:6379"

  collab-mongodb:
    image: mongo:latest
    container_name: collaboration-service-mongodb
    # expose port for testing purposes or to view database in MongoDB Compass
    ports:
      - "27019:27017"
    volumes:
      - ./collab-mongo-data:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${COLLAB_MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${COLLAB_MONGO_INITDB_ROOT_PASSWORD}
    entrypoint: /bin/sh -c 'if [ -z "$COLLAB_MONGODB_URI" ]; then echo "Starting MongoDB..."; /usr/local/bin/docker-entrypoint.sh mongod; else echo "COLLAB_MONGODB_URI is set. Shutting down."; exit 1; fi'
    restart: no

  g38-collaboration-service:
    image: delishad21/collaboration-service:dev
    env_file:
      - .env  # Loads environment variables from .env file
    environment:
      - COLLAB_MONGODB_URI=${COLLAB_MONGODB_URI:-mongodb://${COLLAB_MONGO_INITDB_ROOT_USERNAME}:${COLLAB_MONGO_INITDB_ROOT_PASSWORD}@collab-mongodb:27017/collaboration-service?authSource=admin}  # Fallback to local MongoDB if MONGODB_URI is not set
    ports:
      - "${COLLAB_SERVICE_PORT}:${COLLAB_SERVICE_PORT}"  # Bind port using env variable
    depends_on:
      - collab-redis
    network_mode: "host"
