apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab-service
  labels:
    app: collab-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collab-service
  template:
    metadata:
      labels:
        app: collab-service
    spec:
      containers:
        - name: collab-service
          image: asia-southeast1-docker.pkg.dev/peerprep-437117/peerprep/collaboration-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8010
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
            - configMapRef:
                name: collab-config
            - secretRef:
                name: collab-secrets
          resources:
            limits:
              memory: "1Gi"
              cpu: "250m"
